### ISSUE TITLE
[BUG] Dark Mode Disappears when restarting 

### ISSUE THREAD

**Issue by michmich112** [nelioyann/grithub#1]
# Reproduction method
## Web (Chrome): 
1.  Open app.grithub.fr
2. Go to your account
3. Turn the dark mode `on` in the settings page
4. Refresh the page

### Expected Result:
App is in dark mode.

### Actual result:
App is in light mode.

**Comment by nelioyann** [comment]
Fixed in b33032566179b9dd2b3b8d9a507c5463c04a2531
