### ISSUE TITLE
[FT] Edit a habit description

### ISSUE THREAD

**Issue by michmich112** [nelioyann/grithub#5]
# Feature Request
As a Grithub User
I would like to edit the description of a Habit
So thatit suits/describes the habit I want to keep

Note: the name of this habit should not be changed in the past for consistency
Note: The name of the habit can only be shared it the habit is active (not deleted)

**Comment by nelioyann** [comment]
There's currently no description associated to each habit, do you mean to provide a way to add one different than the habit name ?

**Comment by michmich112** [comment]
Appologies, i used title and description the same. I mean if i created a habit called "Do 100 push ups a day" but i want to update it to "Do 120 push ups a day" without deleting the habit altogether
